// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrWKwSScsGrJLvTpGnyFSW6bPVSd0cVFU',
    appId: '1:533405057969:web:eb4b8a871052b1f7b7f390',
    messagingSenderId: '533405057969',
    projectId: 'asahi-todo',
    authDomain: 'asahi-todo.firebaseapp.com',
    storageBucket: 'asahi-todo.appspot.com',
    measurementId: 'G-QN5D2X4C2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJh7qgSfKChtxRmXMiO8hwTYf666R4tjo',
    appId: '1:533405057969:android:57b99df8fbb9b345b7f390',
    messagingSenderId: '533405057969',
    projectId: 'asahi-todo',
    storageBucket: 'asahi-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCozopKlLahQuJUy-L6V1jqMVEmDaZBJ-4',
    appId: '1:533405057969:ios:8d3e3342cfb05fffb7f390',
    messagingSenderId: '533405057969',
    projectId: 'asahi-todo',
    storageBucket: 'asahi-todo.appspot.com',
    iosBundleId: 'com.example.asahiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCozopKlLahQuJUy-L6V1jqMVEmDaZBJ-4',
    appId: '1:533405057969:ios:8cb30a26b4b29a3cb7f390',
    messagingSenderId: '533405057969',
    projectId: 'asahi-todo',
    storageBucket: 'asahi-todo.appspot.com',
    iosBundleId: 'com.example.asahiTodo.RunnerTests',
  );
}
